name: Build project

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_TYPE: Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update submodule
        run: git submodule update --recursive --init --depth 1

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build g++

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            version: '6.5'
            host: 'linux'

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}

      - name: Build with CMake
        run: |
          cd build
          cmake --build .